/**
 * This file was generated by the Jeddict
 */
package com.iko.iko.domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @author win 10
 */
@Entity
@Table(name = "iko_note")
public class Note {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private Double valeur;

    @ManyToOne(targetEntity = User.class)
    private User user;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getValeur() {
        return this.valeur;
    }

    public void setValeur(Double valeur) {
        this.valeur = valeur;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}